#!/bin/bash

### BEGIN INIT INFO
# Provides:          nturt ros on docker 
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts nturt ros on docker
# Description:       starts nturt ros on docker, this script assumes that you already created a
#                    container named "ros" container using NRURacingTeam/docker repository and
#                    put the launch file for roslaunch in /ws/src of the container path
### END INIT INFO

# /etc/init.d/nturt_ros

start() {
    echo -n "Starting nturt ros on docker: "
    echo "--------------------------------------------------" >> /var/log/nturt_ros
    date +"! %Y/%m/%d %a %T : Launching ros on docker" >>/var/log/nturt_ros
    # if docker contianer is not running
    if [[ -n $(docker container list -a | sed -n '2,$p' | awk '{print $NF}' | grep -w ros) ]]; then
        # run docker container wooht name "ros"
        docker start ros
    fi
    # configure can hat
    ip link set down can0
    ip link set can0 type can bitrate 250000 restart-ms 100
    # turn on can hat
    ifconfig can0 up
    # launch ros in docker
    docker exec -d ros bash -c "source /opt/ros/noetic/setup.bash
                                source \${HOME}/ws/devel/setup.bash
                                roslaunch nturt_deploy_to_rpi nturt_ros.launch"
    date +"! %Y/%m/%d %a %T : Finished launching ros on docker." >>/var/log/nturt_ros
    echo "--------------------------------------------------" >> /var/log/nturt_ros
    echo "Done"
    # create a lock file to prevent re-run of this file
    touch /var/lock/subsys/nturt_ros
}

stop() {
    echo -n "Shuting down nturt ros on docker: "
    echo "--------------------------------------------------" >> /var/log/nturt_ros
    date +"! %Y/%m/%d %a %T : Shuting down ros on docker" >>/var/log/nturt_ros
    # find the pid of rosmaster that's running in the docker container
    ROS_MASTER_PID=$(pgrep rosmaster)
    # kill "nturt_ros_launch.py" process, which will also shutdown ros
    docker exec -d ros pkill -f roslaunch
    # wait until rosmaster is shutdown
    wait ${ROS_MASTER_PID}
    date +"! %Y/%m/%d %a %T : Finished shuting down ros on docker." >>/var/log/nturt_ros
    echo "--------------------------------------------------" >> /var/log/nturt_ros
    echo "Done"
    # remove the lock file
    rm /var/lock/subsys/nturt_ros
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        stop
        start
    ;;
    *)
        echo "Usage: nturt_ros { start | stop | restart }"
        exit 1
    ;;
esac
exit 0
