#!/bin/bash

### BEGIN INIT INFO
# Provides:          nturt ros on docker 
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts nturt ros on docker
# Description:       starts nturt ros on docker, this script assumes that you already created a
#                    container named "ross" container using NRURacingTeam/docker repository and
#                    put the launch file for roslaunch in /ws/src of the container path
### END INIT INFO

# /etc/init.d/nturt_ros

NTURT_ROS_DIRECTORY="/"

start() {
    echo -n "Starting nturt ros on docker: "
    echo "--------------------------------------------------" >> /var/log/nturt_ros
    date +"! %Y/%m/%d %a %T : Launching ros on docker" >>/var/log/nturt_ros
    # if docker contianer is not running
    if [[ -n $(docker container list -a | sed -n '2,$p' | awk '{print $NF}' | grep -w ros2) ]]; then
        # run docker container with name "ros2"
        docker start ros2
    fi

    # launch ros2 in docker
    docker exec -d ros2 bash -c "source /opt/ros/\${ROS_DISTRO}/setup.bash
                                 source \${HOME}/ws/install/setup.bash
                                 ros2 launch nturt_rpi_deployer nturt_ros.launch.py"
    date +"! %Y/%m/%d %a %T : Finished launching ros on docker." >>/var/log/nturt_ros

    # start executing loop for executing host command in docker container
    ${NTURT_ROS_DIRECTORY}/scripts/execute_loop.sh ${NTURT_ROS_DIRECTORY} &
    disown -h %1

    echo "--------------------------------------------------" >> /var/log/nturt_ros
    echo "Done"
    # create a lock file to prevent re-run of this file
    touch /var/lock/subsys/nturt_ros
}

stop() {
    echo -n "Shuting down nturt ros on docker: "
    echo "--------------------------------------------------" >> /var/log/nturt_ros
    date +"! %Y/%m/%d %a %T : Shuting down ros on docker" >>/var/log/nturt_ros

    # stop ros2 docker container
    docker stop ros2

    # stop executing loop
    echo stop > ${NTURT_ROS_DIRECTORY}/nturt_ros_pipe &

    date +"! %Y/%m/%d %a %T : Finished shuting down ros on docker." >>/var/log/nturt_ros
    echo "--------------------------------------------------" >> /var/log/nturt_ros
    echo "Done"
    # remove the lock file
    rm /var/lock/subsys/nturt_ros
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        stop
        start
    ;;
    *)
        echo "Usage: nturt_ros { start | stop | restart }"
        exit 1
    ;;
esac
exit 0
